### PR TITLE
API template scripts update_bid_offer deprecation

### PR DESCRIPTION
**Pull request by chrisd12**

### CODE REVIEW

**Comment by Hassan754** [comment]
@chrisd12 you should add the update_existing=True to these function calls to make it behave like the deprecated update_offer function

**Comment by chrisd12** [comment]
https://github.com/gridsingularity/d3a-api-client/blob/master/d3a_api_client/commands.py#L43-L44 @Hassan754 is this really required since replace_existing is True by default?

**Comment by Hassan754** [comment]
Ah missed it, it's okay then
LGTM

**Review by Hassan754 — APPROVED** [review]

**Review by hannesdiedrich — APPROVED** [review]
LGTM

**Pull request merged**
