### PR TITLE
D3ASIM-3651: Add flake8 as pre-commit hook

### PR DESCRIPTION
**Pull request by faizan2590**

### CODE REVIEW

**Review by spyrostz — APPROVED** [review]
I am not sure if this was discussed, but why not copying the whole content of the d3a precommit hook (as far as I see, in addition to flake, we also have multiple pre-commit hooks in d3a)? Is it because we will add pylint anyways, so it is an overkill to also check it via pre-commit ? 

LGTM once this is discussed

**Comment by fievelk** [comment]
> I am not sure if this was discussed, but why not copying the whole content of the d3a precommit hook (as far as I see, in addition to flake, we also have multiple pre-commit hooks in d3a)? Is it because we will add pylint anyways, so it is an overkill to also check it via pre-commit?

@spyrostz I'm adding pylint and two other pre-commit hooks in a different PR (https://github.com/gridsingularity/d3a-api-client/pull/180). Should I add other hooks?

**Comment by spyrostz** [comment]
> > I am not sure if this was discussed, but why not copying the whole content of the d3a precommit hook (as far as I see, in addition to flake, we also have multiple pre-commit hooks in d3a)? Is it because we will add pylint anyways, so it is an overkill to also check it via pre-commit?
> 
> @spyrostz I'm adding pylint and two other pre-commit hooks in a different PR (#180). Should I add other hooks?

IMO it would be great if all hooks were synced, you can see the ones we currently use in d3a here https://github.com/gridsingularity/d3a/blob/master/.pre-commit-config.yaml

**Comment by fievelk** [comment]
> > > I am not sure if this was discussed, but why not copying the whole content of the d3a precommit hook (as far as I see, in addition to flake, we also have multiple pre-commit hooks in d3a)? Is it because we will add pylint anyways, so it is an overkill to also check it via pre-commit?
> > 
> > 
> > @spyrostz I'm adding pylint and two other pre-commit hooks in a different PR (#180). Should I add other hooks?
> 
> IMO it would be great if all hooks were synced across repos (not automatically, manually copying the hooks would do), therefore it would be great if you ported all of them from d3a to the other repos. You can see the ones we currently use in d3a here https://github.com/gridsingularity/d3a/blob/master/.pre-commit-config.yaml

Ok, I'll update the PRs 👍

**Review by fievelk — APPROVED** [review]

**Pull request merged**
